export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCTS_RANDOM = "GET_PRODUCTS_RANDOM";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const GET_ALL_WAIST = "GET_ALL_WAIST";
export const FILTER_BY_WAIST = "FILTER_BY_WAIST";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
